export const SCREENSHOT_RECORD_FIELDS = [
  'ID',
  'Player',
  'ELO',
  'Result',
  'Opponent',
  'Opponent ELO',
  'Tournament',
  'Date',
  '1st Serve %',
  'Aces',
  'Double Faults',
  'Fastest Serve',
  'Avg 1st Serve Speed',
  'Avg 2nd Serve Speed',
  'Winners',
  'Forced Errors',
  'Unforced Errors',
  'Net Points Won %',
  'Break Points Won %',
  'Total Points Won',
  'Short Rallies Won (<5) %',
  'Medium Rallies Won (5-8) %',
  'Long Rallies Won (>8) %',
  'Average Rally Length',
  'Set Points Saved',
  'Match Points Saved',
  '1st Serve Won %',
  '2nd Serve Won %',
  'Return Points Won %',
  'Return Winners',
  'Breaks / Games %',
  'Character',
  'Opponent Character',
  '1st Serve Return Points Won %',
  '2nd Serve Return Points Won %',
  'Break Points Saved %',
  'Tie-breaks Won %',
  'Deciding Sets Won %',
  'Review Status',
] as const;

export const SCREENSHOT_METRIC_FIELDS = [
  'ELO',
  'Opponent ELO',
  '1st Serve %',
  'Aces',
  'Double Faults',
  'Fastest Serve',
  'Avg 1st Serve Speed',
  'Avg 2nd Serve Speed',
  'Winners',
  'Forced Errors',
  'Unforced Errors',
  'Net Points Won %',
  'Break Points Won %',
  'Total Points Won',
  'Short Rallies Won (<5) %',
  'Medium Rallies Won (5-8) %',
  'Long Rallies Won (>8) %',
  'Average Rally Length',
  'Set Points Saved',
  'Match Points Saved',
  '1st Serve Won %',
  '2nd Serve Won %',
  'Return Points Won %',
  'Return Winners',
  'Breaks / Games %',
  '1st Serve Return Points Won %',
  '2nd Serve Return Points Won %',
  'Break Points Saved %',
  'Tie-breaks Won %',
  'Deciding Sets Won %',
] as const;

export const SCREENSHOT_REVIEW_STATUSES = [
  'FOR REVIEW',
  'DAVIS CUP',
  'DUPLICATE',
] as const;

export type ScreenshotRecordData = Partial<
  Record<(typeof SCREENSHOT_RECORD_FIELDS)[number], string | number>
> & Record<string, string | number | undefined>;